/**
 * Autogenerated by Thrift Compiler (0.11.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.zhenhui.demo.uic.api.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

@Data
public class UserDto implements Serializable {

    private static final long serialVersionUID = -7557856224910228683L;

    public Long id;

    public String name;

    public String avatar;

    public Set<String> authorities = new HashSet<>();

}

